server:
  port: 8080  # Client service runs on port 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
    fetch-registry: true  # Enable fetching registry updates from Eureka server
    register-with-eureka: true  # Register this service with Eureka server
  instance:
    lease-renewal-interval-in-seconds: 5  # Frequency of heartbeats (default is 30 seconds)
    lease-expiration-duration-in-seconds: 10  # Time after which Eureka marks instance as down (default is 90 seconds)
    prefer-ip-address: true  # Prefer using the IP address over hostname

spring:
  application:
    name: "user"
  datasource:
    url: jdbc:mysql://localhost:3306/DataBase
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      name: user

redis:
  host: localhost
  port: 6379
  password: root@123

